-- MySQL Script generated by MySQL Workbench
-- Sun Mar  3 21:28:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dealer_java
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dealer_java
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dealer_java` DEFAULT CHARACTER SET utf8 ;
USE `dealer_java` ;

-- -----------------------------------------------------
-- Table `dealer_java`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dealer_java`.`Users` (
  `IDuser` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`IDuser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dealer_java`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dealer_java`.`Brand` (
  `IDbrand` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `state` TINYINT NOT NULL,
  PRIMARY KEY (`IDbrand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dealer_java`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dealer_java`.`Vehicle` (
  `IDvehicle` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `year` VARCHAR(4) NOT NULL,
  `color` VARCHAR(10) NOT NULL,
  `img` BLOB NULL,
  `price` DOUBLE NOT NULL,
  `stock` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `state` TINYINT NOT NULL,
  `IDbrand` INT NOT NULL,
  PRIMARY KEY (`IDvehicle`),
  INDEX `fk_Vehicle_Brand1_idx` (`IDbrand` ASC),
  CONSTRAINT `fk_Vehicle_Brand1`
    FOREIGN KEY (`IDbrand`)
    REFERENCES `dealer_java`.`Brand` (`IDbrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dealer_java`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dealer_java`.`Client` (
  `IDclient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `age` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`IDclient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dealer_java`.`Sales_Detalil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dealer_java`.`Sales_Detalil` (
  `idSale` INT NOT NULL AUTO_INCREMENT,
  `IDvehicle` INT NOT NULL,
  `IDclient` INT NOT NULL,
  `price_sale` DOUBLE NOT NULL,
  `discount` DOUBLE NOT NULL,
  `date` DATETIME NOT NULL,
  INDEX `fk_Vehicle_has_Client_Client1_idx` (`IDclient` ASC),
  INDEX `fk_Vehicle_has_Client_Vehicle_idx` (`IDvehicle` ASC),
  PRIMARY KEY (`idSale`),
  CONSTRAINT `fk_Vehicle_has_Client_Vehicle`
    FOREIGN KEY (`IDvehicle`)
    REFERENCES `dealer_java`.`Vehicle` (`IDvehicle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicle_has_Client_Client1`
    FOREIGN KEY (`IDclient`)
    REFERENCES `dealer_java`.`Client` (`IDclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
