package model;
// Generated Mar 26, 2019 4:38:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer idclient;
     private String name;
     private String surname;
     private String lname;
     private String phone;
     private String address;
     private String age;
     private Set salesDetalils = new HashSet(0);

    public Client() {
    }

	
    public Client(String name, String surname, String lname, String phone, String address, String age) {
        this.name = name;
        this.surname = surname;
        this.lname = lname;
        this.phone = phone;
        this.address = address;
        this.age = age;
    }
    public Client(String name, String surname, String lname, String phone, String address, String age, Set salesDetalils) {
       this.name = name;
       this.surname = surname;
       this.lname = lname;
       this.phone = phone;
       this.address = address;
       this.age = age;
       this.salesDetalils = salesDetalils;
    }
   
    public Integer getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(Integer idclient) {
        this.idclient = idclient;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public Set getSalesDetalils() {
        return this.salesDetalils;
    }
    
    public void setSalesDetalils(Set salesDetalils) {
        this.salesDetalils = salesDetalils;
    }




}


