package model;
// Generated Mar 26, 2019 4:38:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by RAledesma
 */
public class Vehicle  implements java.io.Serializable {


     private Integer idvehicle;
     private Brand brand;
     private String model;
     private String year;
     private String color;
     private byte[] img;
     private double price;
     private int stock;
     private String description;
     private byte state;
     private Set salesDetalils = new HashSet(0);

    public Vehicle() {
    }

	
    public Vehicle(Brand brand, String model, String year, String color, double price, int stock, String description, byte state) {
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.color = color;
        this.price = price;
        this.stock = stock;
        this.description = description;
        this.state = state;
    }
    public Vehicle(Brand brand, String model, String year, String color, byte[] img, double price, int stock, String description, byte state, Set salesDetalils) {
       this.brand = brand;
       this.model = model;
       this.year = year;
       this.color = color;
       this.img = img;
       this.price = price;
       this.stock = stock;
       this.description = description;
       this.state = state;
       this.salesDetalils = salesDetalils;
    }
   
    public Integer getIdvehicle() {
        return this.idvehicle;
    }
    
    public void setIdvehicle(Integer idvehicle) {
        this.idvehicle = idvehicle;
    }
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public byte[] getImg() {
        return this.img;
    }
    
    public void setImg(byte[] img) {
        this.img = img;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getState() {
        return this.state;
    }
    
    public void setState(byte state) {
        this.state = state;
    }
    public Set getSalesDetalils() {
        return this.salesDetalils;
    }
    
    public void setSalesDetalils(Set salesDetalils) {
        this.salesDetalils = salesDetalils;
    }




}


